
USE ROLE ACCOUNTADMIN;

CREATE ROLE METABASE_SERVICE_ROLE;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE METABASE_SERVICE_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE METABASE_SERVICE_ROLE;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE METABASE_SERVICE_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE METABASE_SERVICE_ROLE;
GRANT MONITOR USAGE ON ACCOUNT TO  ROLE  METABASE_SERVICE_ROLE;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE METABASE_SERVICE_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE METABASE_SERVICE_ROLE;

CREATE USER METABASE_SERVICE_USER;

GRANT ROLE METABASE_SERVICE_ROLE TO USER METABASE_SERVICE_USER;

GRANT ROLE METABASE_SERVICE_ROLE TO ROLE SYSADMIN;

USE ROLE METABASE_SERVICE_ROLE;


CREATE OR REPLACE DATABASE METABASE_DB;
USE DATABASE METABASE_DB;

CREATE OR REPLACE WAREHOUSE METABASE_WH
WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;


CREATE COMPUTE POOL IF NOT EXISTS METABASE_COMPUTE_POOL
MIN_NODES = 1
MAX_NODES = 1
INSTANCE_FAMILY = CPU_X64_XS;




--CREATE THE SERVICE USER 


--





