

--STOP! BEFORE YOU PROCEED MAKE SURE YOU UPLOAD YOUR YAML AND YOU MAKE AND UPLOAD THE IMAGES

USE ROLE METABASE_SERVICE_ROLE;
USE DATABASE METABASE_DB;

CREATE SERVICE METABASE_DB.PUBLIC.METABASE_SERVICE
IN COMPUTE POOL METABASE_COMPUTE_POOL
FROM @specs
specification_file='metabase.yaml'
EXTERNAL_ACCESS_INTEGRATIONS = (METABASE_EXTERNAL_ACCESS);